### ISSUE TITLE
Cannot release

### ISSUE THREAD

**Issue by davidbrochart** [jupyterlab/jupyter-collaboration#265] opened 2024-03-28 09:28 UTC
## Description

I tried to release jupyter-collaboration but it seems that I can't anymore. I did change my PyPI token recently but I updated it in my fork of jupyter-releaser's secrets. I also tried self-releasing, but that failed too.
Maybe @blink1073 has ideas?

**Comment by jtpio** [comment] 2024-03-28 10:03
I think we should update the workflows: https://github.com/jupyterlab/jupyter-collaboration/issues/262

**Comment by davidbrochart** [comment] 2024-03-28 11:26
@blink1073 it failed at the [NPM stage](https://github.com/jupyterlab/jupyter-collaboration/actions/runs/8466462028/job/23195265689).

**Comment by blink1073** [comment] 2024-03-28 11:32
Ugh, I pushed this change to the wrong remote, can you please apply this diff?

```
--- a/.github/workflows/publish-release.yml
+++ b/.github/workflows/publish-release.yml
@@ -38,6 +38,8 @@ jobs:

       - name: Finalize Release
         id: finalize-release
+        env:
+          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
         uses: jupyter-server/jupyter_releaser/.github/actions/finalize-release@v2
         with:
           token: ${{ steps.app-token.outputs.token }}
```

**Comment by davidbrochart** [comment] 2024-03-28 12:50
hmm stil [failing](https://github.com/jupyterlab/jupyter-collaboration/actions/runs/8467453021/job/23198313710).

**Comment by blink1073** [comment] 2024-03-28 13:57
I just set it to the npm token for the `@jupyter` org.

**Comment by davidbrochart** [comment] 2024-03-28 14:28
Not sure it was that, see [this](https://github.com/jupyterlab/jupyter-collaboration/actions/runs/8468740996/job/23202463044#step:5:198).

**Comment by blink1073** [comment] 2024-03-28 14:52
I'm not sure, I don't work in npm-land anymore.  :)

**Comment by krassowski** [comment] 2024-03-29 14:06
Cryptic `npm ERR! code E404` - great! I asked on https://github.com/npm/feedback/discussions/1099.

**Comment by krassowski** [comment] 2024-03-29 16:02
I think that the problem is with configuration on npm. I do not see `@jupyter-releaser-bot` as a contributor listed there, even though it is listed on https://www.npmjs.com/package/@jupyter-notebook/application

It looks like the release went through half an hour ago but without provenance, I guess someone uploaded it manually? https://www.npmjs.com/package/@jupyter/collaboration

**Comment by krassowski** [comment] 2024-03-29 16:08
I think I do not have permissions to add the bot to the appropriate team or add the package to the team where the bot is. @jtpio can you take a look?

**Comment by davidbrochart** [comment] 2024-03-29 16:15
@Zsailer did a manual release, thank you!
- https://github.com/jupyterlab/jupyter-collaboration/releases/tag/v2.0.11
- https://pypi.org/project/jupyter-collaboration/2.0.11/
- https://www.npmjs.com/package/@jupyter/collaboration/v/2.0.8

**Comment by jtpio** [comment] 2024-03-29 16:26
OK the `jupyter-releaser-bot` npm account should now be a member of the `jupyter` organization.

**Comment by jtpio** [comment] 2024-03-29 16:34
I don't know if npm plans to implement something like the PyPI trusted publishers. But if they do we could get rid of that bot.

**Comment by blink1073** [comment] 2024-03-29 16:38
Supposedly it is coming eventually: https://github.blog/2023-04-19-introducing-npm-package-provenance/#looking-ahead

**Comment by krassowski** [comment] 2024-04-16 11:05
@davidbrochart I will try to make a new *alpha* release using the GH action to see if everything is in order after the recent refactor https://github.com/jupyterlab/jupyter-collaboration/pull/280.

**Comment by krassowski** [comment] 2024-04-16 11:57
The upload step failed:

```
Fetching PyPI API token...
Handling dist file dist/jupyter-collaboration-3.0.0-alpha.0.tgz
COMMAND: npm publish --tag next jupyter-collaboration-3.0.0-alpha.0.tgz
Handling dist file dist/jupyter-collaboration-extension-3.0.0-alpha.0.tgz
COMMAND: npm publish --tag next jupyter-collaboration-extension-3.0.0-alpha.0.tgz
Handling dist file dist/jupyter-docprovider-3.0.0-alpha.0.tgz
COMMAND: npm publish --tag next jupyter-docprovider-3.0.0-alpha.0.tgz
Handling dist file dist/jupyter-docprovider-extension-3.0.0-alpha.0.tgz
COMMAND: npm publish --tag next jupyter-docprovider-extension-3.0.0-alpha.0.tgz
Handling dist file dist/jupyter_collaboration-3.0.0a0-py3-none-any.whl
/home/runner/work/_actions/jupyter-server/jupyter_releaser/v2/jupyter_releaser/cli.py:676: UserWarning: Python package name jupyter-collaboration does not match with name in jupyter releaser config: jupyter_docprovider. Skipping uploading dist file dist/jupyter_collaboration-3.0.0a0-py3-none-any.whl
  lib.publish_assets(
Handling dist file dist/jupyter_collaboration-3.0.0a0.tar.gz
/home/runner/work/_actions/jupyter-server/jupyter_releaser/v2/jupyter_releaser/cli.py:676: UserWarning: Python package name jupyter-collaboration does not match with name in jupyter releaser config: jupyter_docprovider. Skipping uploading dist file dist/jupyter_collaboration-3.0.0a0.tar.gz
  lib.publish_assets(
Handling dist file dist/jupyter_collaboration_ui-1.0.0a0-py3-none-any.whl
/home/runner/work/_actions/jupyter-server/jupyter_releaser/v2/jupyter_releaser/cli.py:676: UserWarning: Python package name jupyter-collaboration-ui does not match with name in jupyter releaser config: jupyter_docprovider. Skipping uploading dist file dist/jupyter_collaboration_ui-1.0.0a0-py3-none-any.whl
  lib.publish_assets(
Handling dist file dist/jupyter_collaboration_ui-1.0.0a0.tar.gz
/home/runner/work/_actions/jupyter-server/jupyter_releaser/v2/jupyter_releaser/cli.py:676: UserWarning: Python package name jupyter-collaboration-ui does not match with name in jupyter releaser config: jupyter_docprovider. Skipping uploading dist file dist/jupyter_collaboration_ui-1.0.0a0.tar.gz
  lib.publish_assets(
Handling dist file dist/jupyter_docprovider-1.0.0a0-py3-none-any.whl
/home/runner/work/_actions/jupyter-server/jupyter_releaser/v2/jupyter_releaser/cli.py:676: UserWarning: Python package name jupyter-docprovider does not match with name in jupyter releaser config: jupyter_docprovider. Skipping uploading dist file dist/jupyter_docprovider-1.0.0a0-py3-none-any.whl
  lib.publish_assets(
Handling dist file dist/jupyter_docprovider-1.0.0a0.tar.gz
/home/runner/work/_actions/jupyter-server/jupyter_releaser/v2/jupyter_releaser/cli.py:676: UserWarning: Python package name jupyter-docprovider does not match with name in jupyter releaser config: jupyter_docprovider. Skipping uploading dist file dist/jupyter_docprovider-1.0.0a0.tar.gz
  lib.publish_assets(
Handling dist file dist/jupyter_server_ydoc-1.0.0a0-py3-none-any.whl
/home/runner/work/_actions/jupyter-server/jupyter_releaser/v2/jupyter_releaser/cli.py:676: UserWarning: Python package name jupyter-server-ydoc does not match with name in jupyter releaser config: jupyter_docprovider. Skipping uploading dist file dist/jupyter_server_ydoc-1.0.0a0-py3-none-any.whl
  lib.publish_assets(
Handling dist file dist/jupyter_server_ydoc-1.0.0a0.tar.gz
/home/runner/work/_actions/jupyter-server/jupyter_releaser/v2/jupyter_releaser/cli.py:676: UserWarning: Python package name jupyter-server-ydoc does not match with name in jupyter releaser config: jupyter_docprovider. Skipping uploading dist file dist/jupyter_server_ydoc-1.0.0a0.tar.gz
  lib.publish_assets(
```

It looks like releaser compares the name of each python packages against `jupyter_docprovider` (not sure why) and gives up.

The packages for releaser are defined in:

https://github.com/jupyterlab/jupyter-collaboration/blob/a3b498471ace2b47f430984531ef8b98e68bc40f/pyproject.toml#L61-L69

Looking at the `jupyter-releaser` source [here](https://github.com/jupyter-server/jupyter_releaser/blob/e727e2126a5f8d911d056e21bf64b6b610559493/jupyter_releaser/cli.py#L661-L689) it is not clear why it would be comparing against a fixed string each time.

**Comment by krassowski** [comment] 2024-04-19 21:35
So the upload issue should be fixed by https://github.com/jupyter-server/jupyter_releaser/pull/568, but the check release is failing with:

```
ValueError: Tag v1.0.0 already exists! To delete run: `git push --delete origin {tag_name}`
```

I opened https://github.com/jupyter-server/jupyter_releaser/pull/570 proposing a fix for this.

**Comment by Zsailer** [comment] 2024-05-01 04:12
I think this is fixed now.

I was able to make a release, [3.0.0.alpha1](https://github.com/jupyterlab/jupyter-collaboration/releases/tag/v3.0.0alpha1), so closing this issue for now.

**Closed by Zsailer** 2024-05-01 04:12 UTC
Labels: bug
